spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_test_strategies_dev
    username: root
    password:
    name: spring_boot_test_strategies_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
